version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    command: python run.py

  web-prod:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 wsgi:app